### ISSUE TITLE
fails when the installed version of spago  > 0.12.1

### ISSUE THREAD

**Issue by Benjmhart** [justinwoo/spago2nix#26]
with the latest release of spago, installed through npm,  the output of `spago2nix generate` is 

```
getting packages..
got 6 packages from Spago list-packages.
(JSONError "ForeignError: Unexpected token U in JSON at position 0")
```

this is likely due to the command change to `spago ls packages`

**Comment by Benjmhart** [comment]
current workaround is to temporarily install an older version of spago to run the spago2nix generate command or possibly to use a lower version of spago as a project dependency and wrap `spago2nix generate`as an npm script

**Comment by justinwoo** [comment]
could you please make a PR where you make the change here (https://github.com/justinwoo/spago2nix/blob/32ba33ce8d18648a1c47d4388323a3e115f552dd/src/Generate.purs#L48) and update the bin script?

**Comment by Benjmhart** [comment]
@Justinwoo - I'm happy to make the PR, however isn't it a better choice to detect the version of spago upfront and change the command based on the version?

**Comment by justinwoo** [comment]
i think you can really just make some assumptions about the latest version being used and just put it in some changelog as needed. most usages will end up using easy-purescript-nix and such to lock down versions in any case
