### ISSUE TITLE
`spago2nix generate` failed

### ISSUE THREAD

**Issue by justinlovinger** [justinwoo/spago2nix#29]
Using the latest spago2nix from easy-purescript-nix, running `spago2nix generate` gives error

```
getting packages..
Failed to list packages:
Invalid argument `ls'
```
Perhaps it should be `spago list-packages`?

**Comment by justinlovinger** [comment]
I see that a recent pull request (<https://github.com/justinwoo/spago2nix/pull/27>) changed `spago list-packages` to `spago ls packages`, because a newer `spago` changed the syntax. However, it didn't update `spago` used by the Nix package.

**Comment by dhess** [comment]
Same here.
