### ISSUE TITLE
Rate-limiting

### ISSUE THREAD

**Issue by dhess** [justinwoo/spago2nix#31]
Maybe this is just something that happens on macOS, but running `spago2nix generate` on a skeleton Halogen project starts over 1200 `git fetch` processes at once. This effectively locks up the filesystem on my iMac Pro.

It'd be nice to support some sort of rate limit on the number of processes that are started at once.

**Comment by justinwoo** [comment]
https://github.com/justinwoo/spago2nix/blob/878337ea2c89735116c0fc129cb932f9a90a9358/src/Generate.purs#L232
