### ISSUE TITLE
spago2nix with spago --config

### ISSUE THREAD

**Issue by jamesdbrock** [justinwoo/spago2nix#46]
I'm in a situation where I need to run `spago2nix` on a `spago-extra.dhall`.

The `spago-extra.dhall` includes `spago.dhall`.

I'm pretty sure there's no good way to do this with `spago2nix`, right?

**Comment by justinwoo** [comment]
Does this require forwarding some flags or something?

**Comment by jamesdbrock** [comment]
Yeah, forwarding flags to `spago` would suffice.

**Comment by jamesdbrock** [comment]
We could forward the `--config` flag.

**Comment by justinwoo** [comment]
Simplest would probably to just make a function for `List String -> Maybe SpagoArgs` that we just parse out anything after `--`, so we don't have to do any more work in the future when these inevitably change

**Comment by justinwoo** [comment]
looking at this now
