### ISSUE TITLE
NodeJS v10.x is EoL

### ISSUE THREAD

**Issue by toastal** [justinwoo/spago2nix#50]
```shell-session
error: Package ‘nodejs-10.24.1’ in /nix/store/bwvj37279glrmh4bipw0lw0dqgsl7gfi-source/pkgs/development/web/nodejs/v10.nix:11 is marked as insecure, refusing to evaluate.
```

While trying to use `spago2nix` via `easy-purescript-nix` after upgrading to a later pinned version in my flakes, I could no longer use my Nix shell.

**Comment by williamyaoh** [comment]
this issue seems to be here, because #51 updated the `default.nix` but not the `shell.nix`.
